### ISSUE TITLE
Evaluation on outdoor datasets

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [MARSLab-UMN/DeepMultiviewDepth#2]
Hi, your paper looks very interesting, I will definitely check out this repository.  But I'm curious, is there a reason why you do not evaluate on outdoor datasets?

**Comment by MathLens** [comment]
Thanks for your interest. We evaluate on indoor datasets because we focus on indoor applications like 3D scene/objects reconstruction in this work and our future work.
