### ISSUE TITLE
Typo in Equation (1) and (2)?

### ISSUE THREAD

**Issue by yan99033** [MARSLab-UMN/DeepMultiviewDepth#5]
![image](https://user-images.githubusercontent.com/26388965/104768257-91207b00-572a-11eb-81f8-93f1aaa38b40.png)

Since ^1u_i is an image point, I think you are doing back-projection and transformation, so that the cross product of the two vectors are supposed to be zero (since they should be pointing in the same direction)

Edit:
But wait, to match the vectors, I think you would also need to convert ^ku_i to world coordinate frame, i.e., [^kx_i - cx, ^ky_i - cy, 1].

I didn't go through your code so maybe you can clarify the matter.

**Comment by MathLens** [comment]
Sorry, I did not get your first point. I agree with your statement but what is wrong with (1) based on your statement?

For intrinsic matrix K, you are right. We meant applying K^-1 to the points before passing to the loss, but forgot to describe it in the text. Thanks for pointing it out.

**Comment by yan99033** [comment]
![image](https://user-images.githubusercontent.com/26388965/104776416-49542080-5737-11eb-84c0-8c434dd8da16.png)

So, there are two ways to align the two vector:
1. either you subtract the camera centre from the image point ^ku_i (as I mentioned above), or
2. reproject the world point to the image plane by pre-multiplying K to the second vector

I am assuming you are doing either one in your code, or else it won't be working as intended

**Comment by MathLens** [comment]
We did 1, i.e., there should have been a K^-1 before ^k u_i and ^1 u_i in equation (1). By multiplying K^-1, the camera center is subtracted from the pixel coordinates.

**Comment by yan99033** [comment]
I see. Yes, pre-multiplying K^-1 to both ^k u_i and ^1 u_i would work.
