### ISSUE TITLE
Question regarding the evaluation protocol

### ISSUE THREAD

**Issue by baegwangbin** [MARSLab-UMN/DeepMultiviewDepth#6]
Hi, 

I was wondering if you did the median matching (where you multiply the prediction by "median(gt)/median(pred)") during evaluation as Flow2Depth and DeepV2D did.

Thanks

**Comment by MathLens** [comment]
No. The datasets used here have metric scale in the poses so the predict depths and ground-truth depths are already in the same scale.

**Comment by baegwangbin** [comment]
Thanks!
