### ISSUE TITLE
About the comparison with DeepV2D.

### ISSUE THREAD

**Issue by chenerg** [MARSLab-UMN/DeepMultiviewDepth#8]
Why the results of DeepV2D is different from those reported from the DeepV2D paper?  

1. from your paper
![image](https://user-images.githubusercontent.com/24982715/144746449-859dc69f-9413-4b3c-8e50-ad7478186610.png)

2. from paper DeepV2D
![image](https://user-images.githubusercontent.com/24982715/144746454-f6c6adc3-6208-4735-bf18-ef1b1b8d10df.png)

**Comment by MathLens** [comment]
1. We used different train/test split in our experiments.
2. We assume the poses are given at inference time.

**Comment by chenerg** [comment]
Thanks! Sorry to bother you again, where can I find your train/test split?

**Comment by tonyke1993** [comment]
> Thanks! Sorry to bother you again, where can I find your train/test split?

It is not included in this repo. We can upload it online if you need it.

**Comment by MathLens** [comment]
The split we used is the same one in [13], from Robust Vision Challenge at CVPR 2018.

**Comment by chenerg** [comment]
Got it! Thank you very much.
